---
- name: Install Dependencies
  apt:
    name: "ca-certificates"
    state: present
  become: yes
- name: Copy Certificate to store
  copy:
    src: "{{ certificate }}"
    dest: "/usr/local/share/ca-certificates/{{ certificate_rename }}"
  become: yes
- name: Update CA Store
  shell: update-ca-certificates
  become: yes
