---
- name: Install dependencies
  yum:
    name: ca-certificates
    state: present
  become: yes
- name: Enable Updating of CA Trust
  shell: update-ca-trust enable
  become: yes
- name: Copy certificate over
  copy:
    src: "{{ certificate }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ certificate_rename }}"
  become: yes
- name: Update CA Store
  shell: update-ca-trust extract
  become: yes
